name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy: 
    needs: [build]
    runs-on: ubuntu-latest
        steps:

            -uses: actions/checkout@v3
            -name: Install Vercel CLI
             run: npm install --global vercel

            -name: Pull Vercel Environment Information
             run: vercel pull --yes --environment=production --tocken= ${{secrets.FirstToken}}

             -name: Build Project Artifacts
              run: vercel build --prod --token= ${{secrets.FirstToken}}

             -name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --prod --token= ${{secrets.FirstToken}}

# name: Vercel Production Deployment

# env: 
#     VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
#     VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

# on:
#     push:
#          branches:
#               -main

# jobs:
#     Deploy-Production:
#         runs-on: ubuntu-latest
#         steps:

#             -uses: actions/checkout@v3
#             -name: Install Vercel CLI
#              run: npm install --global vercel

#             -name: Pull Vercel Environment Information
#              run: vercel pull --yes --environment=production --tocken= ${{secrets.VERCEL_TOKEN}}

#              -name: Build Project Artifacts
#               run: vercel build --prod --token= ${{secrets.VERCEL_TOKEN}}

#              -name: Deploy Project Artifacts
#               run: vercel deploy --prebuilt --prod --token= ${{secrets.VERCEL_TOKEN}}